# Mark Recapture Distance Sampling

## Introduction

Mark Recapture Distance Sampling (MRDS) combines the principles of mark-recapture and standard distance sampling. 2 observers each travel along the same transect and record the animals they see and the perpendicular distance. By including the capture history of each animal we have enough information to allow for non-zero detection probability on the line, but we lose the pooling robustness property, so unmodelled heterogeneity will cause biased estimates.

Point independence models, which assume the two observers' detection probabilities are uncorrelated at a specific distance, are less biased when faced with unmodelled heterogeneity than full independence models, which assume detection probabilities are independent at all distances. However, the estimates are still negatively biased in this situation. Unmodelled heterogeneity is likely to occur in most surveys as the observers are unlikely to be aware of every potential source of difference in detection and it is not feasible to record multitudes of information whilst moving along a transect.

One advantage of MRDS is that the extra data from the capture history means that it can be used for situations where the probability of detection on the line is not one. This can be useful for marine surveys, where animals on the transect line may be below the water and so not visible, or surveys in thickly forested areas where it is possible to not see animals high up in the canopy. 

This model also assumes that the observers perfectly match which animals they both saw and which ones only one observer saw. If the animals don't have uniquely identifying features and there is any kind of animal movement between surveys then this assumption will not hold.


## Conclusion
MRDS should be used in situations where it is suspected p(0) may be less than one and animals are uniformly distributed and uniquely identifiable. If it is used, the observers should collect as much information as is practical to prevent any unmodelled heterogeneity from causing bias. 
From our simulations, MRDS does not perform well in scenarios with non-uniform animal distribution. It is negatively biased when animals initially avoid the line and positively biased when they are attracted to it.  Imperfect matching has different effects depending on the type of animal movement but makes the estimates much more variable. 

## Futher Reading

Buckland, S.T., Rexstad, E.A., Marques, T.A. and Oedekoven, C.S. (2015). Distance Sampling: Methods and Applications. Springer International Publish, pp.99--103.

Borchers, D.L., Laake, J.L., Southwell, C. and Paxton, C.G.M. (2005). Accommodating Unmodeled Heterogeneity in Double-Observer Distance Sampling Surveys. *Biometrics*, [online] 62(2), pp.372--378. doi:<https://doi.org/10.1111/j.1541-0420.2005.00493.x.>

Burt, M.L., Borchers, D.L., Jenkins, K.J. and Marques, T.A. (2014). Using mark-recapture distance sampling methods on line transect surveys. Methods in Ecology and Evolution, [online] 5(11), pp.1180--1191. <doi:https://doi.org/10.1111/2041-210x.12294>.
