# Simulation

Simulation studies have become indispensable in ecology and conservation research, providing a controlled and repeatable approach to evaluate the performance of estimation methods. In this study, we aimed to assess how each method performs using a range of scenarios with varying degrees of assumption compliance and violations. In each scenario, artificial datasets are created with with known population sizes, density patterns, detectability patterns, etc. to test the accuracy and precision of estimators.

## Simulation scenarios

### Initial perpendicular distance distribution

Perpendicular distance refers to the minimum distance to the transect line at which animals are detected. 3 different levels are considered: uniformly distributed, avoiding the line and attracted to the line.

```{r initial perp. dist. distribution}
par(mfrow=c(1,3))
xs <- seq(0,1,length=100)

# uniformly distributed
plot(xs, pi.const(x=xs,logphi=NA,w=1),
     type='l',xlab='Perp. distance, x',ylab=expression(pi(x)))

# avoiding the line
plot(xs, pi.chnorm(x=xs,logphi=c(0, -0.5),w=1),
     type='l',xlab='Perp. distance, x',ylab=expression(pi(x)))

# attracted to the line
plot(xs,pi.norm(x=xs,logphi=c(0, 1),w=1),
     type='l',xlab='Perp. distance, x',ylab=expression(pi(x)))

```
